//I AM ZARMAIN
/*I AM A STUDENT OF CERTIFIED CLOUD APLLIED AI GENERATIVE ENGINEER
date5/3/2024
THIS IS MY FIRST PROGRAMM*/
console.log(`HELLO GOVERNOR SINDH KAMRAN KHAN TESSORI , THANK YOU`);


//KEYWORD Ctrl+/ 